name: Build, Provision

on:
  workflow_dispatch:

  push:
    branches: [main]
jobs:
  build:
    uses: alexeygnetko/angular-and-s3/.github/workflows/build-angular.yml@main
  provision:
    uses: alexeygnetko/angular-and-s3/.github/workflows/provision-aws.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws-region: eu-west-1
